#27 sticky footer
hagenstrahl/anna-otto pull request #71
Opened 2024-12-05 05:43 UTC by behindadyingstar

2024-12-05 18:32 UTC, hagenstrahl requested changes
Test:

- [x] Laut Design soll es kein border-top geben
- [x] Desktop: Die Elemente sind zueinander nicht zentriert ausgerichtet
- [ ] Mobile: Clickbaren Bereich der Links sollte mindestens 48x48px betragen (Ist für den Nutzer leichter, mit dem Finger zu treffen)
- [x] Desktop: Die Social Media Links haben nicht das richtige Spacing.
- [x] Deskotp: Alle Links sollten auch einen klickbaren Bereich von mindesten 48x48px haben
- [ ] Desktop: Logo sollte zur Homepage routen

2024-12-05 18:32 UTC, hagenstrahl commented on apps/website/__tests__/components/external-link.test.tsx
> +        testId={propsWithDefaults.testId}
`{...propsWithDefaults}` ...

2024-12-05 18:32 UTC, hagenstrahl commented on apps/website/__tests__/components/external-link.test.tsx
> +    props?: ExternalLinkProps
`Partial` ...

2024-12-05 18:32 UTC, hagenstrahl commented on apps/website/app/page.tsx
> +      <DesktopFooter />
Müssen die nicht in die layout.tsx? Die sollen doch auf jeder Seite dargestellt werden?

2024-12-05 18:32 UTC, hagenstrahl commented on apps/website/components/desktop-footer.tsx
> +          <span className="text-grau">Beratung</span>
Vielleicht noch "(Comming soon)" oder ganz weglassen?

2024-12-05 18:32 UTC, hagenstrahl commented on apps/website/components/external-link.tsx
> +export interface ExternalLinkProps {
Interfaces benutzen und dann className und testId hier entfernen

2024-12-05 18:32 UTC, hagenstrahl commented on apps/website/components/heading.tsx
> +export interface HeadingProps {
Interfaces benutzen und überflüssige properties entfernen

2024-12-05 18:32 UTC, hagenstrahl commented on apps/website/components/heading.tsx
> +export interface HeadingProps {
Auch eine TestId hinzufügen. Wir werden häufig mehrere Headings haben, damit man die unterscheiden kann

2024-12-05 18:32 UTC, hagenstrahl commented on apps/website/components/mobile-footer.tsx
> +          <a
ExternalLink

2024-12-08 21:52 UTC, behindadyingstar commented on apps/website/components/desktop-footer.tsx
> +          <span className="text-grau">Beratung</span>
mit dem Zusatz "coming soon" sieht es komisch aus weil der text zu lang ist, also habe ich es komplett weggelassen

2024-12-09 18:47 UTC, hagenstrahl requested changes

2024-12-09 18:47 UTC, hagenstrahl commented on apps/website/components/heading.tsx
> +  testId = "heading",
Nicht vorbelegen

2024-12-09 18:47 UTC, hagenstrahl commented on apps/website/components/heading.tsx
> +          data-testid={testId}
util function benutzen

2024-12-12 16:06 UTC, hagenstrahl requested changes
Nur noch Kleinigkeiten ... wir sollten keinen Code behalten, der keine Wirkung hat

2024-12-12 16:06 UTC, hagenstrahl commented on apps/website/components/mobile-footer.tsx
> +            <Phone className="w-6 h-6" />
```suggestion
            <Phone />
```
Die Breiten und Höhenangaben, hatten keine Auswirkung, richtig?

2024-12-12 16:06 UTC, hagenstrahl commented on apps/website/components/mobile-footer.tsx
> +            <Mail className="w-6 h-6" />
```suggestion
            <Mail />
```

2024-12-12 16:06 UTC, hagenstrahl commented on apps/website/components/mobile-footer.tsx
> +            <Map className="w-6 h-6" />
```suggestion
            <Map />
```

2024-12-12 16:06 UTC, hagenstrahl commented on apps/website/components/mobile-footer.tsx
> +            <Facebook className="w-6 h-6" />
```suggestion
            <Facebook />
```

2024-12-12 16:06 UTC, hagenstrahl commented on apps/website/components/mobile-footer.tsx
> +            <Instagram className="w-6 h-6" />
```suggestion
            <Instagram />
```

2024-12-12 16:06 UTC, hagenstrahl commented on apps/website/components/desktop-footer.tsx
> +            <Instagram className="w-6 h-6" />
```suggestion
            <Instagram />
```

2024-12-12 16:06 UTC, hagenstrahl commented on apps/website/components/desktop-footer.tsx
> +            <Facebook className="w-6 h-6" />
```suggestion
            <Facebook />
```

2024-12-17 18:45 UTC, hagenstrahl approved these changes

2024-12-17 18:52 UTC, merged